services:
  postgres:
    image: postgres:17-alpine
    container_name: donbosco_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: donbosco
      POSTGRES_PASSWORD: donbosco
      POSTGRES_DB: donbosco
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
